apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-calico-cluster   
  region: us-west-2
  version: '1.18'
nodeGroups:
  - name: ng-my-calico-cluster
    instanceType: t3.medium
    minSize: 0
    maxSize: 4
    desiredCapacity: 4
    amiFamily: Bottlerocket
    iam:
      attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
